### ISSUE TITLE
missing dependant - wine ?

### ISSUE THREAD

**Issue by garfield69** [DuckieTV/duckietv-builder#1]
Trying out duckietv-builder. goal: to build a windows x32 binary, but not publish it.    
I'm a first time user of npm, but managed to install or resolve most of the pre-requisites for running the builder (on a windows7 platform).    

`duckietv-builder prepare --nightly --platform windows` step worked fine.    
`duckietv-builder make-binaries --nightly --platform windows` fell over during a step that did an exec wine which I don't have.     
what is wine, and can you point me to the appropriate support page?

**Comment by SchizoDuckie** [comment]
Oof. I haven't thought about that one yet.

Wine Is Not an Emulator, but it allows you to run windows applications on linux.
It's used to execute ResourceHacker.exe on linux. I can make this optional. Hold on.

**Comment by SchizoDuckie** [comment]
I recommend to git clone the repo while we're developing this, more stuff could come up.

**Comment by garfield69** [comment]
>I recommend to git clone the repo while we're developing this, more stuff could come up.    

yup, way ahead of you on this one, already using a cloned repo on my windows GitHub desktop :-)

**Comment by garfield69** [comment]
successfully created and ran a win32 duckietv nightly 20170208 installer package using duckietv-builder  from a win7 platform! \o/

**Comment by SchizoDuckie** [comment]
Woohoo! \o/

**Comment by SchizoDuckie** [comment]
That's pretty fricking awesome since I haven't tested it on windows for a second lol

**Comment by garfield69** [comment]
\o/ setup DuckieTV-builder on my Ubuntu 16.10 sandbox, and used it to build a Debian x32 Nightly package locally which I then Installed successfully.     
So now I can test any changes I make to the DuckieTV-builder suite before I push to the GitHub repo :tada:

**Comment by garfield69** [comment]
Rolling along now. :train:  Able to generate an osx package from my Ubunto duckietv-builder! Took some doing, had to fetch development builds for python, libxml2, libcrypto before fragging xar would compile. Next on my list, packaging windows... tomorrow. I need sleep. :sleeping_bed:

**Comment by SchizoDuckie** [comment]
Excellent! Yea xar is a bitch but it's amazing that it works.

Get your sleep indeed before you start the x11 headless nightmare

Op 12 feb. 2017 10:04 a.m. schreef "garfield69" <notifications@github.com>:

**Comment by garfield69** [comment]
F'ing wine and resource hacker! for some reason on my Ubuntu 16.10 32bit, the duckietv-builder exec of wine resourcehacker with any command line parameters crashes.    
yet, running wine resourcehacker directly and using the gui to perform the commands works!     
I'm deep into winedbg to try figure out what is going on :-/

**Comment by SchizoDuckie** [comment]
Show me the crash log

**Comment by SchizoDuckie** [comment]
also, welcome to the x11 headless nightmare :rofl:

**Comment by SchizoDuckie** [comment]
This is what my cronjob does on headless linux-server:
 
```
 /root/startx && /root/duckietv-builder/duckietv-builder make-binaries --nightly 
```
So it fires 2 commands in succession, startx and the builder.
Startx looks like this:

```
export DISPLAY=:0.0
Xvfb :0.0 -screen 0 1900x1080x16 &
``` 
(it has chmod +x to make it executable and makes sure that the x-framebuffer is running and a screen is defined.)

**Comment by garfield69** [comment]
>Show me the crash log     

first screencapture with the resourcehacker messagebox open and the terminal log:
![image](https://cloud.githubusercontent.com/assets/6933240/23054524/3ec18bb0-f545-11e6-9785-40117202233d.png)
second screencapture with the resourcehacker messagebox closed and the rest of the terminal log:
![image](https://cloud.githubusercontent.com/assets/6933240/23054551/620507dc-f545-11e6-882e-1b12e9e9cebb.png)

**Comment by SchizoDuckie** [comment]
Uh wow. Those are new to me too. Have you had any luck?

All I can think of is that you should maybe try using winetricks to install some runtime libraries like the vc++ runtimes. (even though ResourceHacker is a Delphi program this should help with some of the components used

Also,this could help: 
http://nazar-blog.com/2015/08/wine-error-unhandled-exception-0x0eedfade-and-how-i-solved-it/

**Comment by garfield69** [comment]
I enabled the wine debugger last night, and waded through 40K of logs this morning to discover the problem.     
Then I read the ResourceHacher 4.5.30 guide at http://angusj.com/resourcehacker/ to code the parms to stop the abends.     

Basically, the issue is simply that resourcehacker cannot find the files to operate on, and it is also bitching about the log it cannot write to tell you about the failure.     

I am right this moment putting the finishing touches to a commit that will fix my problem. But I will make it a pull request because I would prefer you check/test it on your server to make sure it has no negative impact.     

I expect to submit the commit in a couple hours, or the end of the day if I other activities require my time :-)
