### ISSUE TITLE
updating the nightly repo

### ISSUE THREAD

**Issue by garfield69** [DuckieTV/duckietv-builder#2]
I've noticed that the https://github.com/DuckieTV/Nightlies repo is not getting clones/updates from the https://github.com/SchizoDuckie/DuckieTV. The DuckieTV-builder is only updating  the Nightly releases.    
This results in the Nightly pre-release tag changelog displaying changes that go back to the last time the nightly repo was updated, an ever growing list as each release is posted.

**Comment by SchizoDuckie** [comment]
Ah, good find. There was a line in the Android builder that pushed the
whole contents of that with - -force, nixing the state.

Op 14 feb. 2017 1:29 a.m. schreef "garfield69" <notifications@github.com>:

**Comment by SchizoDuckie** [comment]
Fixed with 2e1db7efb852fe1a0a3c42f7e65d8d48dcac3925
