### ISSUE TITLE
windows CONVERT != linux CONVERT ;-)

### ISSUE THREAD

**Issue by garfield69** [DuckieTV/duckietv-builder#4]
When running duckietv-builder on the windows platform, the `prepare --nightly --platform newtab,browseraction` fails during the *rotating nightly logos for webstore* stage:
![image](https://cloud.githubusercontent.com/assets/6933240/23090882/b2ae7e70-f60d-11e6-9d5a-61a3169b0f5f.png)
this is because the Windows CLI command *convert* is a FAT volume to NTFS disk command, and not an image converter.

**Comment by Js41637** [comment]
lolfail

**Comment by Js41637** [comment]
why do you need to manually convert it anyway, just save a rotated version lol
