### ISSUE TITLE
android make-binaries or publish not working

### ISSUE THREAD

**Issue by garfield69** [DuckieTV/duckietv-builder#5]
[edit]
The https://github.com/DuckieTV/DuckieTV  repo is not getting daily updates pushed to it since the old buildbot was decommissioned.    The repo has not been updated since 24th January.     
It looks like the duckietv-builder should be updating this repo during the android publish phase, so either that is not working, or the make-binaries phase is broken?      
I don't have a phonegap key, or an android platform, so I cannot test this.

**Comment by garfield69** [comment]
spotted what is going on.     
at several places in the platforms/andriod.js script, *echo* is used instead of *exec*.    
https://github.com/DuckieTV/duckietv-builder/blob/master/platforms/android.js#L136      
https://github.com/DuckieTV/duckietv-builder/blob/master/platforms/android.js#L147

**Comment by SchizoDuckie** [comment]
Good find. I disabled it for easier testing and forgot to re-enable it.
