### ISSUE TITLE
add a scheduled disk cleanup to ensure build server does not run out of space

### ISSUE THREAD

**Issue by garfield69** [DuckieTV/duckietv-builder#7]
The duckietv-builder server hdd needs a regular disk clean up scheduled to free up space for the next build.

**Comment by garfield69** [comment]
ToDo:     
- [x] Garfield69: add a cleanup-binaries command to the duckietv-builder script that empties the binaries folder
- [x] Schizoduckie: once the above is complete, add a cronjob to schedule a `duckietv-builder cleanup-binaries` command.

**Comment by SchizoDuckie** [comment]
Scheduled weekly. Thanks for the assist.
